-- Setup script for snorkeling_spots table in Supabase
-- Run this in your Supabase SQL editor

CREATE TABLE snorkeling_spots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_of_snorkeling_spot TEXT NOT NULL,
    region TEXT, -- General region (e.g., "Culebra", "Fajardo", "San Juan")
    forecast_date DATE,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    forecast_timestamp TIMESTAMP WITH TIME ZONE,
    wave_height NUMERIC,
    wave_period NUMERIC,
    wind_speed NUMERIC,
    wind_direction NUMERIC,
    precipitation_probability NUMERIC,
    wind_gusts NUMERIC,
    cloud_cover NUMERIC,
    temperature NUMERIC,
    precipitation_amount NUMERIC,
    ocean_current_velocity NUMERIC,
    ocean_current_direction NUMERIC,
    sea_level_height NUMERIC,
    swell_wave_direction NUMERIC, -- Direction of the incoming swell
    energy NUMERIC -- Calculated "Snorkeling Suitability Score" (0-100)
);

-- Enable Row Level Security
ALTER TABLE snorkeling_spots ENABLE ROW LEVEL SECURITY;

-- Create policies for snorkeling_spots table
CREATE POLICY "Public read access for snorkeling data" 
ON snorkeling_spots FOR SELECT 
USING (true);

CREATE POLICY "Only service accounts can insert snorkeling data" 
ON snorkeling_spots FOR INSERT 
WITH CHECK (auth.role() = 'service_role');

CREATE POLICY "Only service accounts can update snorkeling data" 
ON snorkeling_spots FOR UPDATE 
USING (auth.role() = 'service_role');

CREATE POLICY "Only service accounts can delete snorkeling data" 
ON snorkeling_spots FOR DELETE 
USING (auth.role() = 'service_role');

-- Create indexes for better query performance
CREATE INDEX idx_snorkeling_spots_name ON snorkeling_spots(name_of_snorkeling_spot);
CREATE INDEX idx_snorkeling_spots_region ON snorkeling_spots(region);
CREATE INDEX idx_snorkeling_spots_forecast_date ON snorkeling_spots(forecast_date);
CREATE INDEX idx_snorkeling_spots_timestamp ON snorkeling_spots(forecast_timestamp);
CREATE INDEX idx_snorkeling_spots_energy ON snorkeling_spots(energy);
CREATE INDEX idx_snorkeling_spots_location ON snorkeling_spots(latitude, longitude);

-- Optional: Create a view for the best snorkeling conditions (energy score >= 75)
CREATE VIEW excellent_snorkeling_conditions AS
SELECT 
    name_of_snorkeling_spot,
    region,
    forecast_timestamp,
    wave_height,
    wind_speed,
    temperature,
    energy
FROM snorkeling_spots
WHERE energy >= 75
ORDER BY energy DESC, forecast_timestamp ASC; 